import { BookOpen, AlertTriangle, Home, DollarSign } from "lucide-react";

const transactionData = [
  {
    id: 1,
    description: "Online Course - React Mastery",
    amount: -199,
    category: "Education",
    type: "expense",
    date: "2025-06-18",
    time: "14:30",
    merchant: "Udemy",
    icon: BookOpen,
    color: "#F4C542",
  },
  {
    id: 2,
    description: "Emergency Fund Deposit",
    amount: 1000,
    category: "Emergency",
    type: "income",
    date: "2025-06-17",
    time: "09:15",
    merchant: "Bank Transfer",
    icon: AlertTriangle,
    color: "#8B1C22",
  },
  {
    id: 3,
    description: "Monthly Rent Payment",
    amount: -700,
    category: "Housing",
    type: "expense",
    date: "2025-06-15",
    time: "08:00",
    merchant: "Property Management",
    icon: Home,
    color: "#22543D",
  },
  {
    id: 4,
    description: "Freelance Payment",
    amount: 850,
    category: "Income",
    type: "income",
    date: "2025-06-14",
    time: "16:45",
    merchant: "Client ABC",
    icon: DollarSign,
    color: "#059669",
  },
  {
    id: 5,
    description: "Programming Books",
    amount: -89,
    category: "Education",
    type: "expense",
    date: "2025-06-13",
    time: "11:20",
    merchant: "Amazon",
    icon: BookOpen,
    color: "#F4C542",
  },
  {
    id: 6,
    description: "Utilities Bill",
    amount: -145,
    category: "Housing",
    type: "expense",
    date: "2025-06-12",
    time: "10:30",
    merchant: "Electric Company",
    icon: Home,
    color: "#22543D",
  },
  {
    id: 7,
    description: "Side Project Income",
    amount: 320,
    category: "Income",
    type: "income",
    date: "2025-06-11",
    time: "19:15",
    merchant: "App Store",
    icon: DollarSign,
    color: "#059669",
  },
  {
    id: 8,
    description: "Certification Course",
    amount: -299,
    category: "Education",
    type: "expense",
    date: "2025-06-10",
    time: "13:45",
    merchant: "Coursera",
    icon: BookOpen,
    color: "#F4C542",
  },
  {
    id: 9,
    description: "Home Insurance",
    amount: -180,
    category: "Housing",
    type: "expense",
    date: "2025-06-09",
    time: "15:20",
    merchant: "Insurance Co.",
    icon: Home,
    color: "#22543D",
  },
  {
    id: 10,
    description: "Emergency Withdrawal",
    amount: -75,
    category: "Emergency",
    type: "expense",
    date: "2025-06-08",
    time: "12:10",
    merchant: "ATM",
    icon: AlertTriangle,
    color: "#8B1C22",
  },
];

export default transactionData;
